description "WojakCoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env WOJAKCOIND_BIN="/usr/bin/wojakcoind"
env WOJAKCOIND_USER="wojakcoin"
env WOJAKCOIND_GROUP="wojakcoin"
env WOJAKCOIND_PIDDIR="/var/run/wojakcoind"
# upstart can't handle variables constructed with other variables
env WOJAKCOIND_PIDFILE="/var/run/wojakcoind/wojakcoind.pid"
env WOJAKCOIND_CONFIGFILE="/etc/wojakcoin/wojakcoin.conf"
env WOJAKCOIND_DATADIR="/var/lib/wojakcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # wojakcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$WOJAKCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run wojakcoind."
        echo "The setting must appear in $WOJAKCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"WojakCoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$WOJAKCOIND_PIDDIR"
    chmod 0755 "$WOJAKCOIND_PIDDIR"
    chown $WOJAKCOIND_USER:$WOJAKCOIND_GROUP "$WOJAKCOIND_PIDDIR"
    chown $WOJAKCOIND_USER:$WOJAKCOIND_GROUP "$WOJAKCOIND_CONFIGFILE"
    chmod 0660 "$WOJAKCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$WOJAKCOIND_PIDFILE" \
    --chuid $WOJAKCOIND_USER:$WOJAKCOIND_GROUP \
    --exec "$WOJAKCOIND_BIN" \
    -- \
    -pid="$WOJAKCOIND_PIDFILE" \
    -conf="$WOJAKCOIND_CONFIGFILE" \
    -datadir="$WOJAKCOIND_DATADIR" \
    -disablewallet \
    -daemon

