#!/usr/bin/env bash
#
#  wojakcoind The wojakcoin core server.
#
#
# chkconfig: 345 80 20
# description: wojakcoind
# processname: wojakcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/wojakcoind, see below
if [ -f /etc/sysconfig/wojakcoind ]; then
        . /etc/sysconfig/wojakcoind
fi

RETVAL=0

prog=wojakcoind
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/wojakcoind
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/wojakcoind}

# wojakcoind defaults to /usr/bin/wojakcoind, override with BITCOIND_BIN
wojakcoind=${BITCOIND_BIN-/usr/bin/wojakcoind}

# wojakcoind opts default to -disablewallet, override with BITCOIND_OPTS
wojakcoind_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $wojakcoind $wojakcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
